name: urban_harvest
description: "An app"

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.4
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  community_material_icon: ^5.4.55

  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  youtube_player_flutter: ^8.1.2

  lottie: ^3.0.0
  http: ^1.2.0
  geolocator: ^11.0.0
  geocoding: ^2.1.1

  tflite_flutter: ^0.9.0
  image: ^3.0.2
  logger: ^2.0.2+1
  tflite_flutter_helper: ^0.2.1
  collection: ^1.18.0
  provider: ^6.1.1
  camera: ^0.10.5+9
  path_provider: ^2.0.3
  image_picker: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/img/search.png

    - assets/img/landing/vegetables/
    - assets/img/landing/flowers/
    - assets/img/landing/greens/
    - assets/img/agriculture.jpg


    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

    - assets/dict.txt
    - assets/model.tflite

  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
