name: urban_harvest
description: "An app"

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.4
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  community_material_icon: ^5.4.55

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/img/search.png

    - assets/img/landing/vegetables/
    - assets/img/landing/flowers/
    - assets/img/landing/greens/
    - assets/img/agriculture.jpg



  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
